---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
  phpcodesniffer:
    enabled: true
  SonarPHP:
    enabled: true
  phan:
    enabled: true
exclude_patterns:
- "tests/"
